[package]
name = "example_issue_quick_xml"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.31.0", features = ["serialize"] }
serde = { version = "1.0.203", features = ["derive"] }
